Repository kothariji/SyntaxMeets, pull requests merged in 2021-03, with the labels that each got.

#53 Improve copy message UI
  frontend/syntaxmeets/package-lock.json
  frontend/syntaxmeets/src/components/Navbar/Navbar.js
Labels: Work In Progress

#59 📚[Docs]: Improve guidelines in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: GSSOC21, Level0, documentation

#61 Issue resolved
  backend/package-lock.json
  frontend/syntaxmeets/src/components/Home/Home.js
Labels: GSSOC21, JS, Level2, Priority: Medium, ux-improvement

#64 Landing Page SVG is now covered
  frontend/syntaxmeets/src/components/Home/Home.module.css
Labels: GSSOC21, Level2, enhancement

#63 ⚒️[Fix]: Improved UI
  frontend/syntaxmeets/src/components/Footer/Footer.module.css
  frontend/syntaxmeets/src/components/SyntaxEditor/LanguageData.js
Labels: CSS, GSSOC21, Level1

#77 Close Button added for ChatBox and ParticipantsList
  frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js
  frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
Labels: GSSOC21, Level1, ux-improvement

#83 Loader component added
  frontend/syntaxmeets/package.json
  frontend/syntaxmeets/src/App.js
  frontend/syntaxmeets/src/components/Loader/Loader.js
  frontend/syntaxmeets/src/components/Loader/Loader.module.css
  frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js
Labels: GSSOC21, Level2, enhancement

#82 [Feat]: Improved chat message UI
  frontend/syntaxmeets/src/components/SyntaxChat/ChatMessage.js
  frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
Labels: CSS, GSSOC21, Level2, PR:Under-Review, ux-improvement

#86 [Feat]: Snackbar for code copied.
  frontend/syntaxmeets/package-lock.json
  frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
Labels: GSSOC21, JS, Level1

#92 Improve security of website [#75 -fixed]
  backend/server/index.js
  backend/server/package-lock.json
  backend/server/package.json
  backend/server/rateLimiter.js
  frontend/syntaxmeets/package-lock.json
Labels: GSSOC21, Level2

#94 Add Emoji picker
  frontend/syntaxmeets/package-lock.json
  frontend/syntaxmeets/package.json
  frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
Labels: GSSOC21, Level2

#95 Changing RoomId copied message
  frontend/syntaxmeets/src/components/Navbar/Navbar.js
Labels: GSSOC21, Level1
