Repository kothariji/SyntaxMeets, pull requests merged in 2021-04, with the labels that each got.

#99 [ Frontend ] Refactored frontend code🔨 / State Management -Redux 🚀
  frontend/syntaxmeets/package-lock.json
  frontend/syntaxmeets/package.json
  frontend/syntaxmeets/src/App.css
  frontend/syntaxmeets/src/App.js
  frontend/syntaxmeets/src/components/Home/Home.js
  frontend/syntaxmeets/src/components/Navbar/Navbar.js
  frontend/syntaxmeets/src/components/SnackBar/Snackbar.js
  frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js
  frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
  frontend/syntaxmeets/src/components/SyntaxEditor/CodeInput.js
  frontend/syntaxmeets/src/components/SyntaxEditor/CodeOutput.js
  frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
  frontend/syntaxmeets/src/components/SyntaxPad/SyntaxPad.js
  frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
  frontend/syntaxmeets/src/index.js
  frontend/syntaxmeets/src/services/axios.js
  frontend/syntaxmeets/src/services/socket.js
  frontend/syntaxmeets/src/store/actions/chatActions.js
  frontend/syntaxmeets/src/store/actions/editorActions.js
  frontend/syntaxmeets/src/store/actions/roomActions.js
  frontend/syntaxmeets/src/store/actions/uiActions.js
  frontend/syntaxmeets/src/store/reducers/chatReducer.js
  frontend/syntaxmeets/src/store/reducers/editorReducer.js
  frontend/syntaxmeets/src/store/reducers/roomReducer.js
  frontend/syntaxmeets/src/store/reducers/uiReducer.js
  frontend/syntaxmeets/src/store/store.js
  frontend/syntaxmeets/src/store/types.js
  frontend/syntaxmeets/src/util/util.js
Labels: GSSOC21, Level3, PR:Under-Review, WOW 🤩

#104 ⚒️[Fix]: Emoji Icon Alignment in ChatBox
  frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
Labels: CSS, GSSOC21, Level1

#108 Long name is now not overflowed
  frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js
Labels: CSS, GSSOC21, Level1

#107 feat: Enter Key will submit forms
  frontend/syntaxmeets/src/components/Home/Home.js
Labels: GSSOC21, Level2

#112 🚀 [FEAT: ] Download code feature
  frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
  frontend/syntaxmeets/src/util/util.js
Labels: GSSOC21, Level2

#116 Alert converted to toast
  frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
Labels: GSSOC21, Level2

#117 Language gets changed on uploading
  frontend/syntaxmeets/src/components/SyntaxEditor/LanguageData.js
  frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
Labels: GSSOC21, Level2

#125 ⚒️[Fix]: Scrollbar Customized
  frontend/syntaxmeets/src/App.css
  frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js
Labels: CSS, GSSOC21, Level2

#126 ⚒️[Fix]: About Creators socials Link CSS fix
  frontend/syntaxmeets/src/components/About/Card/MediaCard.js
Labels: GSSOC21, Level1

#123 🚀[FEAT: ] Focus mode implemented
  frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
  frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
  frontend/syntaxmeets/src/store/actions/editorActions.js
  frontend/syntaxmeets/src/store/actions/uiActions.js
  frontend/syntaxmeets/src/store/reducers/uiReducer.js
  frontend/syntaxmeets/src/store/types.js
Labels: GSSOC21, Level2

#124 Snackbar created
  frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
Labels: GSSOC21, Level2

#127 🚀[Feat]: Reconnect user on refresh issue #69
  backend/server/index.js
  frontend/syntaxmeets/src/components/Home/Home.js
  frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
  frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
  frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
Labels: GSSOC21, Level2, PR:Under-Review
